web_affiliate/history/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views.shop_history import ShopHistory
from .views.customer_history import CustomerHistory
from .views.broker_history import BrokerHistory
from .views.admin_history import AdminHistory


app_name = 'history'


urlpatterns = [
    url(r'^shop_history/$', login_required(ShopHistory.as_view(), login_url='authentications:login'), name="shop_history"),
    url(r'^customer_history/$', login_required(CustomerHistory.as_view(), login_url='authentications:login'), name="customer_history"), 
    url(r'^broker_history/$', login_required(BrokerHistory.as_view(), login_url='authentications:login'), name="broker_history"),
    url(r'^admin_history/$', login_required(AdminHistory.as_view(), login_url='authentications:login'), name="admin_history"),    
]

web_affiliate/web/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from web.views.movement_balance.confirm import ConfirmPayment
from web.views.movement_balance.execute import ExecuteBalanceMovementView
from web.views.movement_balance.balance_movement import BalanceMovementView
from web.views.history import HistoryListView
from web.views.index import index

app_name = 'web'

urlpatterns = [
    url(r'^$', index, name="web-index"),
    url(r'^history/$', HistoryListView.as_view(), name="history"),
    url(r'^movement-balance-execution', ExecuteBalanceMovementView.as_view(), name="execute_movement_balance"),
    url(r'^order/(?P<order_id>[^/]+)/confirm$', ConfirmPayment.as_view(),
        name="confirm_order"),
    url(r'^order/(?P<order_id>[^/]+)/detail', BalanceMovementView.as_view(),
        name="cancel_movement_balance"),
]

web_affiliate/web_affiliate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from web.views.index import health
#
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets
#
from .views import login, transfer_money
#
# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^web_affiliate/admin/', admin.site.urls),
    url(r'^web_affiliate/', include('web.urls')),
    url(r'^web_affiliate/authentications/', include('authentications.urls')),
    url(r'^web_affiliate/profile/', include('profile.urls')),
    url(r'^web_affiliate/health$', health, name="health"),
    url(r'^web_affiliate/wallet/', include('wallet.urls')),
    url(r'^web_affiliate/commision/', include('commision.urls')),
    url(r'^web_affiliate/transaction/', include('transaction.urls')),
    url(r'^web_affiliate/history', include('history.urls')),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^', include(router.urls)),
    url(r'^login', login),
    url(r'^transfer_money', transfer_money)
]

web_affiliate/history/models.py
from django.db import models

# Create your models here.

web_affiliate/history/views/admin_history.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
import requests
from django.contrib import messages
from transaction.models import Transaction
from commision.models import Shop
from authentications.models import Profile


class AdminHistory(TemplateView):
    template_name = 'admin_history.html'

    def get(self, request, *args, **kwargs):
        transactions = []
        context = super(AdminHistory, self).get_context_data(**kwargs)
        
        transaction_history = Transaction.objects.all()
        #transaction_history = Transaction.objects.all().filter(shop_id='0983655001')
        #shop = Shop.objects.get(shop_mobile='0983655001')

        for obj in transaction_history:
            print("shop id is {}".format(obj.shop_id))
            shop = Shop.objects.get(shop_mobile=obj.shop_id)
            transaction = {
                'id':obj.id,
                'bonus':shop.bonus,
                'discount':shop.discount,
                'bill_amount':obj.amount,
                'shop_id':obj.shop_id,
                'broker_id':obj.broker_id,
                'customer_id':obj.customer_id,
                'status':obj.status,
                'transaction_time':obj.transaction_time
            }
            transactions.append(transaction)

        context['transactions'] = transactions
        return render(request, 'admin_history.html', context)

web_affiliate/history/views/broker_history.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
import requests
from django.contrib import messages
from transaction.models import Transaction
from commision.models import Shop
from authentications.models import Profile


class BrokerHistory(TemplateView):
    template_name = 'broker_history.html'

    def get(self, request, *args, **kwargs):
        transactions = []
        context = super(BrokerHistory, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        username = profile.user.username
        
        transaction_history = Transaction.objects.all().filter(broker_id=username)
        
        #transaction_history = Transaction.objects.all().filter(shop_id='0983655001')
        #shop = Shop.objects.get(shop_mobile='0983655001')

        for obj in transaction_history:
            shop = Shop.objects.get(shop_mobile=obj.shop_id)
            transaction = {
                'id':obj.id,
                'bonus':shop.bonus,
                'discount':shop.discount,
                'bill_amount':obj.amount,
                'shop_id':obj.shop_id,
                'customer_id':obj.customer_id,
                'status':obj.status,
                'transaction_time':obj.transaction_time
            }
            transactions.append(transaction)

        context['transactions'] = transactions
        return render(request, 'broker_history.html', context)

web_affiliate/history/views/customer_history.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
import requests
from django.contrib import messages
from transaction.models import Transaction
from commision.models import Customer, Shop
from authentications.models import Profile


class CustomerHistory(TemplateView):
    template_name = 'shop_history.html'

    def get(self, request, *args, **kwargs):
        transactions = []
        context = super(CustomerHistory, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        username = profile.user.username
        
        transaction_history = Transaction.objects.all().filter(customer_id=username)
        
        for obj in transaction_history:
            shop = Shop.objects.get(shop_mobile=obj.shop_id)
            transaction = {
                'id': obj.id,
                'discount': shop.discount,
                'bill_amount': obj.amount,
                'shop_name': obj.shop_id,
                'broker_id': obj.broker_id,
                'status': obj.status,
                'transaction_time': obj.transaction_time
            }
            transactions.append(transaction)

        context['transactions'] = transactions
        return render(request, 'customer_history.html', context)

web_affiliate/history/views/shop_history.py
from django.views.generic.base import TemplateView
from django.shortcuts import render, redirect
import requests
from django.contrib import messages
from transaction.models import Transaction
from commision.models import Shop
from authentications.models import Profile


class ShopHistory(TemplateView):
    template_name = 'shop_history.html'

    def get(self, request, *args, **kwargs):
        transactions = []
        context = super(ShopHistory, self).get_context_data(**kwargs)
        profile = Profile.objects.get(user=self.request.user)
        username = profile.user.username
        
        transaction_history = Transaction.objects.all().filter(shop_id=username)
        #transaction_history = Transaction.objects.all().filter(shop_id='0983655001')
        #shop = Shop.objects.get(shop_mobile='0983655001')
        shop = Shop.objects.get(shop_mobile=username)

        for obj in transaction_history:
            transaction = {
                'id':obj.id,
                'bonus':shop.bonus,
                'discount':shop.discount,
                'bill_amount':obj.amount,
                'broker_id':obj.broker_id,
                'customer_id':obj.customer_id,
                'status':obj.status,
                'transaction_time':obj.transaction_time
            }
            transactions.append(transaction)

        context['transactions'] = transactions
        return render(request, 'shop_history.html', context)

web_affiliate/wallet/views/history.py
from django.views.generic.base import TemplateView
from django.shortcuts import render
import requests
from wallet.models import Wallet



class HistoryView(TemplateView):
    template_name = 'history.html'
    def get(self, request, **kwargs):
        context = super(HistoryView, self).get_context_data(**kwargs)

        url = 'https://api-internal.tmn-dev.com/hackathon/v1/wallet/transactions/history?startDate=2017-08-01&endDate=2017-08-30'

        wallet = Wallet.objects.get(user=self.request.user)
        token = wallet.token_wallet

        response = requests.get(url=url, headers={'access-token': token})
        data = response.json()
        context['history'] = data['data']['activities']
        return render(request, self.template_name, context)

web_affiliate/web/views/history.py
from authentications.models import Authentications
from web_affiliate.utils import setup_logger
from web_affiliate import api_settings
import logging

import requests
from django.conf import settings
from authentications.utils import get_auth_header
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin

logger = logging.getLogger(__name__)


class HistoryListView(LoginRequiredMixin, TemplateView):
    template_name = "history/history.html"
    login_url = 'authentications:login'
    redirect_field_name = 'next'
    logger = logger
    order_url = settings.HOST_NAMES + "payment/" + api_settings.API_VERSION + "/orders"

    def dispatch(self, request, *args, **kwargs):
        self.logger = setup_logger(self.request, logger)
        return super(HistoryListView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        self.logger.info('========== Start get order history list ==========')
        headers = get_auth_header(self.request, self.request.user)
        url = self.order_url
        response = requests.get(url=url, headers=headers, verify=settings.CERT)
        json_data = response.json()
        data = json_data.get('data')
        self.logger.info("Status of response history is {}".format(response.status_code))
        self.logger.info("Request url for get order history is {}".format(url))
        self.logger.info("Response for get order histories are {}".format(len(response.content)))

        if response.status_code == 200 and json_data.get('status', {}).get('code', '') == "success":
            user_id, user_type = self._get_user_id(self.request.user)
            result = {'data': data, 'user_id': int(user_id), 'user_type': user_type}
            self.logger.info('========== End get order history list ==========')
            return result
        else:
            if json_data.get('status', {}).get('code', '') == "access_token_expire":
                # TODO: redirect to login page
                logger.info('========== End get order history list ==========')
                raise Exception(response.content)

        raise Exception(response.content)

    def _get_user_id(self, user):
        user = Authentications.objects.get(user=user)
        correlation_id = user.correlation_id
        data = correlation_id.split("-")
        user_id = data[1]
        user_type = data[0]
        return user_id, user_type

web_affiliate/web/templates/history/history.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="panel mb30">
    <div class="panel-heading border">
        <h3>Order History</h3>
    </div>
    {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
        <div class="col-xs-12">
            <div class="alert alert-danger alert-dismissable" id="msg-role-delete">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                <strong>{{ message }}</strong>
            </div>
        </div>
        {% endif %}
    {% endfor %}
    <div class="panel-body">
        <div class="table-responsive" id=system_user_table>
            <table id="order_history" class="table table-bordered table-striped mb0">
                <thead>
                <tr>
                    <th class="col-sm-1 text-center" id="id">Payee ID</th>
                    <th class="col-sm-1 text-center" id="order_id">Order ID</th>
                    <th class="col-sm-1 text-center" id="ext_transaction_id">External Transaction ID</th>
                    <th class="col-sm-2 text-center" id="date">Date</th>
                    <th class="col-sm-2 text-center" id="amount">Amount</th>
                    <th class="col-sm-1 text-center" id="status">Status</th>
                    <th class="col-sm-1 text-center" id="state">State</th>
                    <th class="col-sm-3 text-center" id="action">Action</th>
                </tr>
                </thead>
                <tbody id="table_body">
                {% for order in data %}
                    {% if user_id == order.payer_user.id or user_id == order.payee_user.id or user_id == order.initiator_user.id %}
                    <tr>
                        <td class="col-sm-1">{{ order.payee_user.id|default_if_none:'' }}</td>
                        <td class="col-sm-1">{{ order.order_id|default_if_none:'' }}</td>
                        <td class="col-sm-1">{{ order.ext_transaction_id|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ order.created_timestamp|default_if_none:'' }}</td>
                        <td class="col-sm-2">{{ order.amount|default_if_none:'' }}</td>
                        <td class="col-sm-1">{{ order.status|default_if_none:'' }}</td>
                        <td class="col-sm-1">{{ order.state|default_if_none:'' }}</td>
                        <td class="col-sm-3">
                            <form class="form-horizontal" role="form" method="post"
                                  {% if order.status == 0 %} visible {% else %} hidden {% endif %}
                                  action="{% url 'web:confirm_order' order.order_id %}">
                                {% csrf_token %}
                                <div class="btn-group">
                                    <a href="{% url 'web:cancel_movement_balance' order.order_id %}">
                                    <input id="client-btn-create-{{order.order_id}}"
                                            class="btn btn-outline btn-primary btn-xs"
                                            type="button" value="details"/>
                                    </a>
                                    <button id="confirm_payment_{{ order.order_id }}"
                                            class="btn btn-outline btn-success btn-xs {% if user_id == order.payer_user.id %} '' {% else %} hidden {% endif %}"
                                            type="submit">
                                        <span>Confirm</span>
                                    </button>
                                </div>
                            </form>
                            <form class="form-horizontal" role="form" method="post"
                                  {% if order.status == 2 %} visible {% else %} hidden {% endif %}
                                  action="{% url 'web:cancel_movement_balance' order.order_id %}">
                                {% csrf_token %}
                                <div class="btn-group">
                                    <a href="{% url 'web:cancel_movement_balance' order.order_id %}">
                                        <input id="client-btn-create-{{order.order_id}}"
                                        class="btn btn-outline btn-primary btn-xs text-left"
                                        type="button" value="details"/>
                                    </a>
                                    <button id="cancel_payment_{{ order.order_id }}"
                                        class="btn btn-outline btn-success btn-xs {% if user_id == order.payee_user.id and user_type == order.payee_user.type %} '' {% else %} hidden {% endif %}"
                                        type="submit">
                                        <span>Cancel</span>
                                    </button>
                                </div>
                            </form>
                            {% if order.status != 2 and order.status != 0 %}
                                <a href="{% url 'web:cancel_movement_balance' order.order_id %}">
                                    <input id="client-btn-create-{{order.order_id}}"
                                    class="btn btn-outline btn-primary btn-xs text-left"
                                    type="button" value="details"/>
                                </a>
                            {% endif %}
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}