web_affiliate/profile/urls.py
from django.conf.urls import url
from .view.detail import UserProfile
from .view.update import UserUpdate
from django.contrib.auth.decorators import login_required

app_name = 'profile'


urlpatterns = [
    url(r'^detail/$', login_required(UserProfile.as_view(), login_url='authentications:login'), name="detail"),
    url(r'^update/$', login_required(UserUpdate.as_view(), login_url='authentications:login'), name="update"),
]

web_affiliate/web/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from web.views.movement_balance.confirm import ConfirmPayment
from web.views.movement_balance.execute import ExecuteBalanceMovementView
from web.views.movement_balance.balance_movement import BalanceMovementView
from web.views.history import HistoryListView
from web.views.index import index

app_name = 'web'

urlpatterns = [
    url(r'^$', index, name="web-index"),
    url(r'^history/$', HistoryListView.as_view(), name="history"),
    url(r'^movement-balance-execution', ExecuteBalanceMovementView.as_view(), name="execute_movement_balance"),
    url(r'^order/(?P<order_id>[^/]+)/confirm$', ConfirmPayment.as_view(),
        name="confirm_order"),
    url(r'^order/(?P<order_id>[^/]+)/detail', BalanceMovementView.as_view(),
        name="cancel_movement_balance"),
]

web_affiliate/web_affiliate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from web.views.index import health
#
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets
#
from .views import login, transfer_money
#
# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^web_affiliate/admin/', admin.site.urls),
    url(r'^web_affiliate/', include('web.urls')),
    url(r'^web_affiliate/authentications/', include('authentications.urls')),
    url(r'^web_affiliate/profile/', include('profile.urls')),
    url(r'^web_affiliate/health$', health, name="health"),
    url(r'^web_affiliate/wallet/', include('wallet.urls')),
    url(r'^web_affiliate/commision/', include('commision.urls')),
    url(r'^web_affiliate/transaction/', include('transaction.urls')),
    url(r'^web_affiliate/history', include('history.urls')),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^', include(router.urls)),
    url(r'^login', login),
    url(r'^transfer_money', transfer_money)
]

web_affiliate/profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    id = models.IntegerField(primary_key=True)
    id_auth_user = models.IntegerField()
    role = models.IntegerField()
    status = models.IntegerField()
    email = models.CharField(max_length=45)
    mobile_phone = models.CharField(max_length=45)

web_affiliate/profile/forms.py
from .models import Profile
from django import forms

	
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('id', 'id_auth_user', 'role', 'status', 'email', 'mobile_phone')

web_affiliate/profile/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="panel mb25">
    <div class="panel-heading border">
        <h3>User Profile</h3>
    </div>
    {% for message in messages %}
    <div class="col-xs-12">
        <div class='alert alert-success alert-dismissable' id="msg-add-service">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <strong>{{ message|capfirst }}</strong>
        </div>
    </div>
    {% endfor %}
    <div class="panel-body">
        <div class="row no-margin">
            <div class="col-lg-12">
                <form id="submit-form" class="form-horizontal" role="form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded"
                                   id="txt_brocker" name="name" value="{{ name }}" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Mobile</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control input-rounded"
                                   id="txt_brocker" name="mobile" value="{{ mobile }}" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded"
                                   id="txt_brocker" name="email" value="{{ email }}" disabled>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Address</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded"
                                   id="txt_brocker" name="address" value="{{ address }}" disabled>
                        </div>
                    </div>
                    <div class="pull-right">
                        <a href="{% url 'profile:update' %}">
                            <input id="btn_cancel" class="btn" type="button" value="Update Profile"/>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web_affiliate/profile/templates/update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="panel mb25">
    <div class="panel-heading border">
        <h3>Update Profile</h3>
    </div>
    {% for message in messages %}
    <div class="col-xs-12">
        <div class='alert alert-success alert-dismissable' id="msg-add-service">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
            <strong>{{ message|capfirst }}</strong>
        </div>
    </div>
    {% endfor %}
    <div class="panel-body">
        <div class="row no-margin">
            <div class="col-lg-12">
                <form id="submit-form" class="form-horizontal" role="form" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Name</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded"
                                   id="txt_brocker" name="name" value="{{ name }}" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Mobile</label>
                        <div class="col-sm-8">
                            <input type="number" class="form-control input-rounded"
                                   id="txt_brocker" name="mobile" value="{{ mobile }}" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-8">
                            <input type="email" class="form-control input-rounded"
                                   id="txt_email" name="email" value="{{ email }}" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Address</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control input-rounded"
                                   id="txt_brocker" name="address" value="{{ address }}" >
                        </div>
                    </div>
                    <div class="pull-right">
                        <a href="{% url 'profile:detail' %}">
                            <input id="btn_cancel" class="btn" type="submit" value="Save"/>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}