web_affiliate/commision/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .view.become_shop import Become_Shop
from .view.become_broker import Become_Broker
from .view.approve_shop import Approve_Shop
from .view.invite_customer import InviteCustomer
from .view.approve_broker import Approve_Broker
from .view.approve_invite_broker import Approve_Invite_Broker
from .view.commission_fee import CommissionFee


app_name = 'commision'

urlpatterns = [
    url(r'^become_shop/$', login_required(Become_Shop.as_view(), login_url='authentications:login'), name="become_shop"),
    url(r'^become_broker/$', login_required(Become_Broker.as_view(), login_url='authentications:login'), name="become_broker"),
    url(r'^approve_shop/$', login_required(Approve_Shop.as_view(), login_url='authentications:login'), name="approve_shop"),
    url(r'^invite_customer/$', login_required(InviteCustomer.as_view(), login_url='authentications:login'), name="invite_customer"),
    url(r'^approve_broker/$', login_required(Approve_Broker.as_view(), login_url='authentications:login'), name="approve_broker"),
    url(r'^approve_invite_broker/$', login_required(Approve_Invite_Broker.as_view(), login_url='authentications:login'), name="approve_invite_broker"),
    url(r'^fee/$', login_required(CommissionFee.as_view(), login_url='authentications:login'), name="commission_fee"),
]

web_affiliate/history/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views.shop_history import ShopHistory
from .views.customer_history import CustomerHistory
from .views.broker_history import BrokerHistory
from .views.admin_history import AdminHistory


app_name = 'history'


urlpatterns = [
    url(r'^shop_history/$', login_required(ShopHistory.as_view(), login_url='authentications:login'), name="shop_history"),
    url(r'^customer_history/$', login_required(CustomerHistory.as_view(), login_url='authentications:login'), name="customer_history"), 
    url(r'^broker_history/$', login_required(BrokerHistory.as_view(), login_url='authentications:login'), name="broker_history"),
    url(r'^admin_history/$', login_required(AdminHistory.as_view(), login_url='authentications:login'), name="admin_history"),    
]

web_affiliate/profile/urls.py
from django.conf.urls import url
from .view.detail import UserProfile
from .view.update import UserUpdate
from django.contrib.auth.decorators import login_required

app_name = 'profile'


urlpatterns = [
    url(r'^detail/$', login_required(UserProfile.as_view(), login_url='authentications:login'), name="detail"),
    url(r'^update/$', login_required(UserUpdate.as_view(), login_url='authentications:login'), name="update"),
]

web_affiliate/wallet/urls.py
from wallet.views.create import WalletCreate
from wallet.views.login import WalletLogin
from wallet.views.topup import Topup
from wallet.views.transfer_money import Transfer_Money
from wallet.views.deposit import Deposit
from wallet.views.history import HistoryView
from django.conf.urls import url
from django.contrib.auth.decorators import login_required


app_name = 'wallet'
login_url = 'authentications:login'

urlpatterns = [
    url(r'^create', login_required(WalletCreate.as_view(), login_url='authentications:login'), name="create"),
    url(r'^login', login_required(WalletLogin.as_view(), login_url='authentications:login'), name="login"),
    url(r'^topup', login_required(Topup.as_view(), login_url='authentications:login'), name="topup"),
    url(r'^transfer_money', login_required(Transfer_Money.as_view(), login_url='authentications:login'), name="transfer_money"),
    url(r'^deposit', login_required(Deposit.as_view(), login_url='authentications:login'), name="deposit"),
    url(r'^history', login_required(HistoryView.as_view(), login_url='authentications:login'), name="history"),
]

web_affiliate/web/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from web.views.movement_balance.confirm import ConfirmPayment
from web.views.movement_balance.execute import ExecuteBalanceMovementView
from web.views.movement_balance.balance_movement import BalanceMovementView
from web.views.history import HistoryListView
from web.views.index import index

app_name = 'web'

urlpatterns = [
    url(r'^$', index, name="web-index"),
    url(r'^history/$', HistoryListView.as_view(), name="history"),
    url(r'^movement-balance-execution', ExecuteBalanceMovementView.as_view(), name="execute_movement_balance"),
    url(r'^order/(?P<order_id>[^/]+)/confirm$', ConfirmPayment.as_view(),
        name="confirm_order"),
    url(r'^order/(?P<order_id>[^/]+)/detail', BalanceMovementView.as_view(),
        name="cancel_movement_balance"),
]

web_affiliate/web_affiliate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from web.views.index import health
#
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets
#
from .views import login, transfer_money
#
# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^web_affiliate/admin/', admin.site.urls),
    url(r'^web_affiliate/', include('web.urls')),
    url(r'^web_affiliate/authentications/', include('authentications.urls')),
    url(r'^web_affiliate/profile/', include('profile.urls')),
    url(r'^web_affiliate/health$', health, name="health"),
    url(r'^web_affiliate/wallet/', include('wallet.urls')),
    url(r'^web_affiliate/commision/', include('commision.urls')),
    url(r'^web_affiliate/transaction/', include('transaction.urls')),
    url(r'^web_affiliate/history', include('history.urls')),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^', include(router.urls)),
    url(r'^login', login),
    url(r'^transfer_money', transfer_money)
]

web_affiliate/templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="">

<head>
    <meta charset="utf-8">
    <title>Affiliate+</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <!-- build:css({.tmp,app}) styles/app.min.css -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/dist/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'styles/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'styles/urban.css' %}">
    <link rel="stylesheet" href="{% static 'styles/urban.skins.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    {% block body_stylesheet %}
    {% endblock %}

</head>
<style type="text/css">
    img{

    }
</style>

<body style="background-color: white;">
{% block body_content %}
<div class="app layout-fixed-header">
    <!--sidebar-panel-->
    {% include 'navigation.html' %}

    <!-- content panel -->
    <div class="main-panel">
        <!-- top header -->
        <header class="header navbar">

            <div class="brand visible-xs">
                <!-- toggle offscreen menu -->
                <div class="toggle-offscreen">
                    <a href="#" class="hamburger-icon visible-xs" data-toggle="offscreen" data-move="ltr">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <!-- /toggle offscreen menu -->
                <!-- logo -->
                <div class="brand-logo">
                    <!--<img src="images/logo-dark.png" height="15" alt="">-->
                </div>
                <!-- /logo -->
                <!-- toggle chat sidebar small screen-->
                <div class="toggle-chat">
                    <a href="javascript:;" class="hamburger-icon v2 visible-xs" data-toggle="layout-chat-open">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
                <!-- /toggle chat sidebar small screen-->
            </div>

            <ul class="nav navbar-nav hidden-xs">
                <li>
                    <!--<p class="navbar-text">-->
                    <!--Native Form Elements-->
                    <!--</p>-->
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right hidden-xs">
                {% if user.is_authenticated %}
                <li>
                    <span id="nav-username" class="navbar-text">{{ user.username }} </span>
                </li>
                {% endif %}
            </ul>

        </header>
        <div class="main-content" style="background-color: white;">
            {% block content %}
            {% endblock %}
        </div>
    </div>

    <footer class="content-footer">
    </footer>
</div>
{% endblock %}
<!-- build:js({.tmp,app}) scripts/app.min.js -->
<script src="{% static 'scripts/extentions/modernizr.js' %}"></script>
<script src="{% static 'vendor/jquery/dist/jquery.js' %}"></script>
<script src="{% static 'vendor/bootstrap/dist/js/bootstrap.js' %}"></script>
<script src="{% static 'vendor/jquery.easing/jquery.easing.js' %}"></script>
<script src="{% static 'vendor/fastclick/lib/fastclick.js' %}"></script>
<script src="{% static 'vendor/onScreen/jquery.onscreen.js' %}"></script>
<script src="{% static 'vendor/jquery-countTo/jquery.countTo.js' %}"></script>
<script src="{% static 'vendor/perfect-scrollbar/js/perfect-scrollbar.jquery.js' %}"></script>
<script src="{% static 'vendor/sweetalert/lib/sweet-alert.min.js' %}"></script>
<script src="{% static 'scripts/ui/accordion.js' %}"></script>
<script src="{% static 'scripts/ui/animate.js' %}"></script>
<script src="{% static 'scripts/ui/link-transition.js' %}"></script>
<script src="{% static 'scripts/ui/panel-controls.js' %}"></script>
<script src="{% static 'scripts/ui/preloader.js' %}"></script>
<script src="{% static 'scripts/ui/toggle.js' %}"></script>
<script src="{% static 'scripts/urban-constants.js' %}"></script>
<script src="{% static 'scripts/extentions/lib.js' %}"></script>
<script src="{% static 'scripts/pages/alert.js' %}"></script>
{% block body_js %}
{% endblock %}

<!-- endbuild -->
</body>

</html>

web_affiliate/templates/navigation.html
{% load permissions_filter %}
{% block sidebar_panel %}
    <div class="sidebar-panel offscreen-left">
        <div class="brand">
            <a href="javascript:;" class="toggle-sidebar hidden-xs hamburger-icon v3"
               data-toggle="layout-small-menu">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </a>
        </div>
        {% with request.resolver_match.url_name as url_name %}
            <nav role="navigation">
                <ul class="nav">
                    {% if user.is_authenticated %}
                        <li class="class={% if url_name == 'web-index' %} active{% endif %}">
                            <a href="{% url 'web:web-index' %}">
                                <i class="fa fa-home"></i>
                                <span>Home</span>
                            </a>
                        </li>
                        <li class="class={% if url_name == 'profile' %} active{% endif %}">
                            <a href="{% url 'profile:detail' %}">
                                <i class="fa fa-user" aria-hidden="true"></i>
                                <span>User Profile</span>
                            </a>
                        </li>
                        <li class="class={% if 'wallet' in request.path %} open{% endif %}">
                            <a href="javascript:;"><i class="fa fa-credit-card"></i><span>Wallet</span></a>
                            <ul class="sub-menu">
                                <li class="{% if url_name == 'create' %}active{% endif %}">
                                    <a href="{% url 'wallet:create' %}"> <span>Create Wallet</span> </a>
                                </li>
                                <li class="{% if url_name == 'login' %}active{% endif %}">
                                    <a href="{% url 'wallet:login' %}"> <span>Login Wallet</span> </a>
                                </li>
                                <li class="{% if url_name == 'topup' %}active{% endif %}">
                                    <a href="{% url 'wallet:topup' %}"> <span>Top-up Money</span> </a>
                                </li>
                                <li class="{% if url_name == 'transfer_money' %}active{% endif %}">
                                    <a href="{% url 'wallet:transfer_money' %}"> <span>Transfer Money</span> </a>
                                </li>
                                <li class="{% if url_name == 'create_permission' %}active{% endif %}">
                                    <a href="{% url 'wallet:history' %}"> <span>Balance & Transaction</span> </a>
                                </li>
                            </ul>
                        </li>
                        <li class="class={% if 'commision' in url_name %} active{% endif %}">
                            <a>
                                <i class="fa fa-area-chart"></i>
                                <span>Configuration</span>
                            </a>
                            <ul class="sub-menu">
                                {% if request.user|has_permission_name:"is_admin" %}
                                    <li class="{% if url_name == 'commision_fee' %}active{% endif %}">
                                        <a href="{% url 'commision:commission_fee' %}"> 
                                        <span>Admin Setup Fee</span>
                                        </a>
                                    </li>
                                    <li class="{% if url_name == 'approve_shop' %}active{% endif %}">
                                        <a href="{% url 'commision:approve_shop' %}"> 
                                        <span>Admin Approve Shop</span>
                                        </a>
                                    </li>
                                {% endif %}
                                {% if request.user|has_permission_name:"is_broker" or request.user|has_permission_name:"is_customer" or request.user|has_permission_name:"is_admin" %}
                                    <li class="{% if url_name == 'become_shop' %}active{% endif %}">
                                        <a href="{% url 'commision:become_shop' %}"> <span>Become Shop</span> </a>
                                    </li>
                                {% endif %}

                                <li class="{% if url_name == 'become_broker' %}active{% endif %}">
                                    <a href="{% url 'commision:become_broker' %}"> <span>Become Broker</span> </a>
                                </li>

                                {% if request.user|has_permission_name:"is_shop" %}
                                    <li class="{% if url_name == 'approve_broker' %}active{% endif %}">
                                        <a href="{% url 'commision:approve_broker' %}"> <span>Shop Approve Broker</span>
                                        </a>
                                    </li>
                                {% endif %}

                                {% if request.user|has_permission_name:"is_broker" %}
                                    <li class="{% if url_name == 'invite_customer' %}active{% endif %}">
                                        <a href="{% url 'commision:invite_customer' %}">
                                            <span>Broker Invite Customer</span> </a>
                                    </li>
                                {% endif %}

                                <li class="{% if url_name == 'approve_invite_broker' %}active{% endif %}">
                                    <a href="{% url 'commision:approve_invite_broker' %}">
                                        <span>Approve Broker Invitation</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        {% if request.user|has_permission_name:"is_broker" or request.user|has_permission_name:"is_customer" or request.user|has_permission_name:"is_shop" or request.user|has_permission_name:"is_admin" %}
                            <li class="class={% if 'transaction' in url_name %} active{% endif %}">
                                <a>
                                    <i class="fa fa-history"></i>
                                    <span>Transaction</span>
                                </a>

                                <ul class="sub-menu">
                                    {% if request.user|has_permission_name:"is_shop" %}
                                    <li class="{% if url_name == 'deposit' %}active{% endif %}">
                                        <a href="{% url 'wallet:deposit' %}"> <span>Shop Deposit</span> </a>
                                    </li>
                                    {%endif%}
                                    {% if request.user|has_permission_name:"is_customer" %}
                                    <li class="{% if url_name == 'discount' %}active{% endif %}">
                                        <a href="{% url 'transaction:discount' %}">
                                            <span>Customer Request Discount</span> </a>
                                    </li>
                                    {%endif%}
                                    {% if request.user|has_permission_name:"is_shop" %}
                                    <li class="{% if url_name == 'confirm' %}active{% endif %}">
                                        <a href="{% url 'transaction:confirm_transaction' %}"> <span>Shop Confirm</span>
                                        </a>
                                    </li>
                                    {%endif%}
                                    {% if request.user|has_permission_name:"is_customer" %}
                                    <li class="{% if url_name == 'payment' %}active{% endif %}">
                                        <a href="{% url 'transaction:payment' %}"> <span>Customer Pay a Bill</span> </a>
                                    </li>
                                    {%endif%}
                                </ul>
                            </li>
                        {% endif %}
                        {% if request.user|has_permission_name:"is_broker" or request.user|has_permission_name:"is_customer" or request.user|has_permission_name:"is_shop" or request.user|has_permission_name:"is_admin" %}
                        <li class="class={% if 'history' in url_name %} active{% endif %}">
                            <a>
                                <i class="fa fa-credit-card"></i>
                                <span>Transaction History</span>
                            </a>
                            {% if request.user|has_permission_name:"is_shop" %}
                            <ul class="sub-menu">
                                <li class="{% if url_name == 'shop_history' %}active{% endif %}">
                                    <a href="{% url 'history:shop_history' %}"> <span>Shop Transaction History</span> </a>
                                </li>
                            </ul>
                            {%endif%}
                            {% if request.user|has_permission_name:"is_customer" %}
                            <ul class="sub-menu">
                                <li class="{% if url_name == 'customer_history' %}active{% endif %}">
                                    <a href="{% url 'history:customer_history' %}"> <span>Customer Transaction History</span> </a>
                                </li>
                            </ul>
                            {%endif%}
                            {% if request.user|has_permission_name:"is_broker" %}
                            <ul class="sub-menu">
                                <li class="{% if url_name == 'broker_history' %}active{% endif %}">
                                    <a href="{% url 'history:broker_history' %}"> <span>Broker Transaction History</span> </a>
                                </li>
                            </ul>
                            {%endif%}
                            <ul class="sub-menu">
                                <li class="{% if url_name == 'admin_history' %}active{% endif %}">
                                    <a href="{% url 'history:admin_history' %}"> <span>All Transaction History</span> </a>
                                </li>
                            </ul>
                        </li>
                        {%endif%}
                        <li>
                            <a href="{% url 'authentications:logout' %}">
                                <i class="fa fa-power-off"></i>
                                <span class="">Logout</span>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endwith %}
    </div>
{% endblock %}

web_affiliate/templates/navigation_backup.html
{% block sidebar_panel %}
<div class="sidebar-panel offscreen-left">
    <div class="brand">
        <a href="javascript:;" class="toggle-sidebar hidden-xs hamburger-icon v3"
           data-toggle="layout-small-menu">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
        </a>
    </div>
    {% with request.resolver_match.url_name as url_name %}
    <nav role="navigation">
        <ul class="nav">
            <li class="class={% if url_name == 'web-index' %} active{% endif %}">
                <a href="{% url 'web:web-index' %}">
                    <i class="fa fa-home"></i>
                    <span>Home</span>
                </a>
            </li>
            <li class="class={% if url_name == 'profile' %} active{% endif %}">
                <a href="{% url 'profile:detail' %}">
                    <i class="fa fa-user" aria-hidden="true"></i>
                    <span>User Profile</span>
                </a>
            </li>
            <li class="class={% if url_name == 'history' %} active{% endif %}">
                <a href="{% url 'web:history' %}">
                    <i class="fa fa-tag"></i>
                    <span>History</span>
                </a>
            </li>
            <li class="class={% if url_name == 'execute_movement_balance' %} active{% endif %}">
                <a href="{% url 'web:execute_movement_balance' %}">
                    <i class="fa fa-area-chart"></i>
                    <span>Balance Movement</span>
                </a>
            </li>
            <li class="class={% if 'wallet' in url_name %} active{% endif %}">
                <a>
                    <i class="fa fa-credit-card"></i>
                    <span>Wallet</span>
                </a>
                <ul class="sub-menu">
                    <li class="{% if url_name == 'link_wallet' %}active{% endif %}">
                        <a href="{% url 'wallet:show' %}"> <span>Create/Link wallet</span> </a>
                    </li>
                    <li class="{% if url_name == 'create_permission' %}active{% endif %}">
                        <a href="#"> <span>Deposit</span> </a>
                    </li>
                    <li class="{% if url_name == 'create_permission' %}active{% endif %}">
                        <a href="#"> <span>Balance & Transection</span> </a>
                    </li>
                </ul>
            </li>
            <li>
                {% if user.is_authenticated %}
                <a href="{% url 'authentications:logout' %}">
                    <i class="fa fa-power-off"></i>
                    <span class="">Logout</span>
                </a>
                {% endif %}
            </li>
        </ul>
    </nav>
    {% endwith %}
</div>
{% endblock %}