web_affiliate/authentications/urls.py
from django.conf.urls import url
from authentications.views import login_form, logout_form, register_form

app_name = 'authentications'

urlpatterns = [
    url(r'^logout/$', logout_form, name='logout'),
    url(r'^login/$', login_form, name='login'),
    url(r'^register/$', register_form, name='register'),
]

web_affiliate/web/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from web.views.movement_balance.confirm import ConfirmPayment
from web.views.movement_balance.execute import ExecuteBalanceMovementView
from web.views.movement_balance.balance_movement import BalanceMovementView
from web.views.history import HistoryListView
from web.views.index import index

app_name = 'web'

urlpatterns = [
    url(r'^$', index, name="web-index"),
    url(r'^history/$', HistoryListView.as_view(), name="history"),
    url(r'^movement-balance-execution', ExecuteBalanceMovementView.as_view(), name="execute_movement_balance"),
    url(r'^order/(?P<order_id>[^/]+)/confirm$', ConfirmPayment.as_view(),
        name="confirm_order"),
    url(r'^order/(?P<order_id>[^/]+)/detail', BalanceMovementView.as_view(),
        name="cancel_movement_balance"),
]

web_affiliate/web_affiliate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from web.views.index import health
#
# from django.contrib.auth.models import User
# from rest_framework import routers, serializers, viewsets
#
from .views import login, transfer_money
#
# # Serializers define the API representation.
# class UserSerializer(serializers.HyperlinkedModelSerializer):
#     class Meta:
#         model = User
#         fields = ('url', 'username', 'email', 'is_staff')
#
# # ViewSets define the view behavior.
# class UserViewSet(viewsets.ModelViewSet):
#     queryset = User.objects.all()
#     serializer_class = UserSerializer
#
# # Routers provide an easy way of automatically determining the URL conf.
# router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

urlpatterns = [
    url(r'^web_affiliate/admin/', admin.site.urls),
    url(r'^web_affiliate/', include('web.urls')),
    url(r'^web_affiliate/authentications/', include('authentications.urls')),
    url(r'^web_affiliate/profile/', include('profile.urls')),
    url(r'^web_affiliate/health$', health, name="health"),
    url(r'^web_affiliate/wallet/', include('wallet.urls')),
    url(r'^web_affiliate/commision/', include('commision.urls')),
    url(r'^web_affiliate/transaction/', include('transaction.urls')),
    url(r'^web_affiliate/history', include('history.urls')),
    # url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    # url(r'^', include(router.urls)),
    url(r'^login', login),
    url(r'^transfer_money', transfer_money)
]

web_affiliate/authentications/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Authentications(models.Model):
    user = models.OneToOneField(User, unique=True)
    access_token = models.CharField(max_length=256)
    last_updated = models.DateTimeField(null=True, blank=True)
    correlation_id = models.CharField(max_length=128, default='')


class Profile(models.Model):
    user = models.OneToOneField(User, unique=True)
    # role = models.IntegerField()
    # mobile = models.CharField(max_length=45)
    permissions = models.CharField(max_length=45)
    address = models.CharField(max_length=130)


@receiver(post_save, sender=User, dispatch_uid='save_new_user_profile')
def save_profile(sender, instance, created, **kwargs):
    user = instance
    if created:
        profile = Profile(user=user)
        profile.save()

web_affiliate/authentications/forms.py
from django import forms
from django.contrib.auth import (
	authenticate,
	get_user_model,
	login,
	logout,
	)

User = get_user_model()

class UserLoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput)

	def clean(self, *args, **kwargs):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		
		if username and password:
			user = authenticate(username=username, password=password)
			if not user:
				print("This user does not exist")
				raise forms.ValidationError("This user does not exist")
			if not user.check_password(password):
				print("Incorect Password")
				raise forms.ValidationError("Incorect Password")
			if not user.is_active:
				print("This user is not longer active")
				raise forms.ValidationError("This user is not longer active")
		return super(UserLoginForm, self).clean(*args, **kwargs)


class UserRegisterForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)
	# address = forms.CharField()

	class Meta:
		model = User
		fields = ('username', 'password', 'first_name')

web_affiliate/authentications/views.py
from django.contrib.auth import logout
from .models import Authentications
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, render
from .forms import UserLoginForm, UserRegisterForm
from hashlib import sha256
from django.contrib import messages


def login_form(request):
    user = None
    if request.user.is_authenticated():
        return redirect('web:web-index')
    else:
        form = UserLoginForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('web:web-index')
    return render(request, "authentications/login.html", {})


def logout_form(request):
    logout(request)
    print("Logout success")
    return render(request, "authentications/login.html", {})


def register_form(request):
    user = None
    if request.user.is_authenticated():
        return redirect('web:web-index')
    else:
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()
                username = form.cleaned_data.get("username")
                first_name = form.cleaned_data['first_name']
                password = form.cleaned_data['password']
                user.set_password(password)
                user.save()
                messages.add_message(
                    request,
                    messages.INFO,
                    'Registration successfully'
                )
            return render(request, "authentications/login.html", {})
        else:
            form = UserRegisterForm()
            return render(request, "authentications/register.html", {})

web_affiliate/wallet/views/login.py
from django.views.generic.base import TemplateView
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect
import requests
from django.contrib import messages
from wallet.models import Wallet
import hashlib


class WalletLogin(TemplateView):
    template_name = 'login_wallet.html'

    def get_context(self, request, **kwargs):
        return render(request, self.template_name)


    def post(self, request, *args, **kwargs):
        api_path = 'https://api-internal.tmn-dev.com/hackathon/v1/wallet/sign-in'
        password = request.POST.get('password')
        username = request.POST.get('username')
        password = hashlib.sha1((username+password).encode('utf-8')).hexdigest()
        params = {
            "username": username,
            "password": password,
            "type": "mobile",
            "deviceToken": "iphone7"
        }
        result = requests.post(url=api_path, headers={'Content-Type': 'application/json'}, json=params)
        result = result.json()

        token = result.get('data').get('access_token')

        # save token to db
        try:
            wallet = Wallet.objects.get(user=self.request.user)
            wallet.wallet_id = username
            wallet.token_wallet = token
            wallet.save()
        except ObjectDoesNotExist:
            Wallet.objects.create(user=self.request.user,
                                  wallet_id=username,
                                  token_wallet=token)

        messages.add_message(
            request,
            messages.SUCCESS,
            'Login Wallet successfully'
        )

        return redirect('web:web-index')

web_affiliate/authentications/templates/authentications/login.html
{% extends "base.html" %}
{% block content %}
    <div class="app layout-fixed-header bg-white usersession">
        <div class="full-height">
            <div class="center-wrapper">
                <div class="center-content">
                    <div class="row no-margin">
                        <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
                            <div action="/" class="form-layout">
                                <div class="text-center mb15">
                                    <!--<img src="images/logo-dark.png"/>-->
                                </div>
                                {% if form.errors %}
                                    <p>Your username and password didn't match. Please try again.</p>
                                {% endif %}

                                {% for message in messages %}
                                    <div class="col-xs-12">
                                        <div class='alert
{#                                            {% if "successfully" in message %}#}
                                            alert-success
{#                                            {% else %}#}
{#                                            alert-danger#}
{#                                            {% endif %}#}
                                            alert-dismissable' id="msg-registration">
                                            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
                                            <strong>{{ message|capfirst }}</strong>
                                        </div>
                                    </div>
                                {% endfor %}

                                {% if next %}
                                    {% if user.is_authenticated %}
                                        <p>Your account doesn't have access to this page. To proceed,
                                            please login with an account that has access.</p>
                                    {% else %}
                                        <p>Please login to see this page.</p>
                                    {% endif %}
                                {% endif %}
                                <form method="post" action="{% url 'authentications:login' %}">
                                    {% csrf_token %}
                                    <div class="form-inputs">
                                        <input id="id_username" maxlength="254" name="username" type="number"
                                               class="form-control input-lg" placeholder="Mobile Number">
                                        <input id="id_password" name="password" type="password"
                                               class="form-control input-lg" placeholder="Password">
                                    </div>
                                    <button id="submitlogin" class="btn btn-success btn-block btn-lg mb15" type="submit"
                                            value="login">
                                        <span>Sign in</span>
                                    </button>
                                    <input type="hidden" name="next" value="{{ next }}"/>
                                    <center><a href="{% url 'authentications:register' %}">Register</a></center>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web_affiliate/authentications/templates/authentications/register.html
{% extends "base.html" %}
{% block content %}
    <div class="app layout-fixed-header bg-white usersession">
        <div class="full-height">
            <div class="center-wrapper">
                <div class="center-content">
                    <div class="row no-margin">
                        <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
                            <div action="/" class="form-layout">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="form-inputs">
                                        <input id="id_username" name="username" type="number"
                                               class="form-control input-lg" placeholder="Mobile *" required>
                                        <input id="id_firstname" name="first_name" type="text"
                                               class="form-control input-lg" placeholder="Name" >
                                        <input id="id_password" name="password" type="password"
                                               class="form-control input-lg" placeholder="Password *" required>
                                    </div>
                                    <button id="submitlogin" class="btn btn-success btn-block btn-lg mb15" type="submit" value="login">
                                        <span>Register</span>
                                    </button>
                                    <input type="hidden" name="next" value="{{ next }}"/>
                                    <center><a href="{% url 'authentications:login' %}">Back to login</a></center>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}